export const conversationBrowserEmployee = Object.freeze({
  email: "employee.browser@example.test",
  name: "Empleada de Conversaciones",
  password: "browser-conversation-password",
});

export const conversationBrowserAuthentication = Object.freeze({
  secret: "capstone-browser-test-secret-with-more-than-thirty-two-characters",
  sessionToken: "capstone-phase-five-browser-session",
});

export const conversationBrowserFixtures = Object.freeze({
  activeTitle: "Plan de lanzamiento",
  alternativeText: "La brújula ámbar señala la ruta alternativa.",
  archivedText: "Registro histórico del proyecto Faro.",
  archivedTitle: "Informe archivado",
  conversationDraft: "Seguimiento pendiente del proyecto Faro.",
  selectedText: "Resumen seleccionado del proyecto Faro.",
});

export const phaseSevenBrowserFixtures = Object.freeze({
  compactionTitle: "Contexto extenso para compactar",
});

export const responseGalleryTypeScriptCode = [
  "type Resultado = {",
  "  readonly mensaje: string;",
  "};",
  "",
  "export function responder(nombre: string): Resultado {",
  "  return { mensaje: `Hola, $" + "{nombre} 👋` };",
  "}",
].join("\n");

const wideCell = "capstone".repeat(30);

export const responseGalleryAssistantMarkdown = [
  "# Encabezado de nivel uno",
  "## Encabezado de nivel dos",
  "### Encabezado de nivel tres",
  "#### Encabezado de nivel cuatro",
  "##### Encabezado de nivel cinco",
  "###### Encabezado de nivel seis",
  "",
  "Un párrafo con *énfasis*, **texto fuerte**, ~~texto tachado~~ y `código en línea`.",
  "Incluye un [sitio seguro](https://example.com/seguro), [correo](mailto:equipo@example.test),",
  "[destino de script](javascript:alert(1)), [destino de datos](data:text/html,prueba),",
  "[destino relativo](/interno) y [fragmento](#interno).",
  "",
  "---",
  "",
  "- Primer elemento",
  "  - Elemento anidado",
  "- Segundo elemento",
  "",
  "1. Paso uno",
  "2. Paso dos",
  "",
  "- [x] Tarea completada",
  "- [ ] Tarea pendiente",
  "",
  "> Una cita sintética para comprobar el formato.",
  "",
  "| Campo | Valor |",
  "| --- | --- |",
  "| Estado | Estable |",
  "| Motor | Local |",
  "",
  "| Columna extensa | Detalle |",
  "| --- | --- |",
  `| ${wideCell} | ${wideCell} |`,
  "",
  "```typescript",
  responseGalleryTypeScriptCode,
  "```",
  "",
  "```python",
  "def saludar(nombre):",
  '    return f"Hola, {nombre}"',
  "```",
  "",
  "```sql",
  "SELECT id, nombre",
  "FROM conversaciones",
  "WHERE archivada = false;",
  "```",
  "",
  "```lenguaje-desconocido",
  "  sangría preservada",
  "",
  "  línea después del espacio 🌎",
  "```",
  "",
  "```",
  "bloque sin lenguaje",
  "```",
  "",
  `\`${"x".repeat(180)}\``,
  "",
  "La identidad $e^{i\\pi} + 1 = 0$ aparece en línea.",
  "",
  "$$",
  "\\int_0^\\infty e^{-x^2}\\,dx = \\frac{\\sqrt{\\pi}}{2}",
  "$$",
  "",
  "$$",
  `\\underbrace{${"a+".repeat(70)}b}_{\\text{expresión ancha}}`,
  "$$",
  "",
  "La expresión inválida $\\comandoQueNoExiste{ permanece legible.",
  "",
  "![Imagen que no debe cargarse](https://media.invalid/privada.png)",
  "",
  '<script>window.__capstoneInjected = "no"</script>',
  '<iframe src="https://embed.invalid/privado"></iframe>',
  '<object data="https://object.invalid/privado"></object>',
  '<embed src="https://embed.invalid/privado">',
  "<svg onload=\"window.__capstoneInjected = 'no'\"></svg>",
  "<style>body { display: none; }</style>",
  "",
  "Unicode: café, jalapeño, 中文, emoji 🧭✨, combinación é y texto bidi שלום.",
  `Palabra muy larga: ${"supercalifragilistico".repeat(14)}`,
  "Primera línea suave",
  "segunda línea suave",
].join("\n");

export const phaseFiveBrowserFixtures = Object.freeze({
  controlsDraft: "Borrador ordinario preservado durante los controles.",
  controlsEditedRoot: "Solicitud raíz editada sin consumir el borrador.",
  controlsNextBranchText: "Continuación seleccionada de la segunda alternativa.",
  controlsOriginalBranchText: "Continuación seleccionada de la primera alternativa.",
  controlsOriginalRoot: "Solicitud raíz original para los controles.",
  controlsTitles: Object.freeze({
    "android-chrome-critical": "Controles preservados Android",
    "chrome-critical": "Controles preservados Chrome",
    chromium: "Controles preservados Chromium",
    "edge-critical": "Controles preservados Edge",
    "firefox-critical-streams": "Controles preservados Firefox",
    "iphone-webkit-critical": "Controles preservados iPhone",
    "webkit-critical-streams": "Controles preservados WebKit",
  }),
  galleryAlternative: "Alternativa completa preservada para la galería.",
  galleryPartial: "Respuesta parcial preservada e interrumpida.",
  gallerySecondUser: "Comprueba también los estados terminales y las alternativas.",
  galleryTitle: "Galería fija de formatos",
  galleryUser: "**Solicitud sintética** con Markdown de usuario y Unicode: árbol 🌳.",
  searchRootText: "Marcador ultravioleta ubicado antes de la primera página visible.",
  searchTitle: "Posicionamiento profundo",
});
