import {
  CONVERSATION_DRAFT_MAX_UTF8_BYTES,
  CONVERSATION_MESSAGE_PAGE_SIZE,
  CONVERSATION_PAGE_SIZE,
  CONVERSATION_SEARCH_PAGE_SIZE,
  CONVERSATION_SEARCH_QUERY_MAX_UTF8_BYTES,
  CONVERSATION_TITLE_MAX_CODE_POINTS,
} from "@capstone/protocol";

export const conversationCoreTuning = Object.freeze({
  branchMessagePageSize: CONVERSATION_MESSAGE_PAGE_SIZE,
  historyPageSize: CONVERSATION_PAGE_SIZE,
  initialTitleCodePoints: 72,
  manualTitleCodePoints: CONVERSATION_TITLE_MAX_CODE_POINTS,
  searchPageSize: CONVERSATION_SEARCH_PAGE_SIZE,
  searchQueryBytes: CONVERSATION_SEARCH_QUERY_MAX_UTF8_BYTES,
  draftBytes: CONVERSATION_DRAFT_MAX_UTF8_BYTES,
  draftRequestBodyBytes: CONVERSATION_DRAFT_MAX_UTF8_BYTES * 2 + 2_048,
});
