export const copy = {
  brand: {
    homeLabel: "Ir al inicio de Capstone Chat",
    productName: "Capstone Chat",
    pageTitle: (title: string) => `${title} | Capstone Chat`,
  },
  service: {
    loading: {
      status: "Verificando el servicio",
    },
    ready: {
      status: "Servicio disponible",
    },
    unavailable: {
      status: "Servicio no disponible",
    },
  },
  identity: {
    common: {
      emailLabel: "Correo electrónico",
      nameLabel: "Nombre",
      currentPasswordLabel: "Contraseña actual",
      newPasswordLabel: "Nueva contraseña",
      confirmPasswordLabel: "Confirmar contraseña",
      passwordLabel: "Contraseña",
      passwordHelp: "Usa entre 12 y 128 caracteres.",
      validationSummary: "Revisa los campos indicados.",
      required: "Este campo es obligatorio.",
      invalidEmail: "Escribe un correo electrónico válido.",
      invalidPasswordLength: "La contraseña debe tener entre 12 y 128 caracteres.",
      passwordsDoNotMatch: "Las contraseñas no coinciden.",
      genericError: "No pudimos completar la solicitud. Inténtalo de nuevo.",
      goToSignIn: "Ir a iniciar sesión",
      backToHome: "Volver al inicio",
    },
    signIn: {
      eyebrow: "Acceso",
      title: "Inicia sesión",
      description: "Usa tu correo de Capstone y tu contraseña.",
      submit: "Iniciar sesión",
      submitting: "Iniciando sesión…",
      error:
        "No pudimos iniciar sesión. Revisa tus datos o verifica tu correo e inténtalo de nuevo.",
      forgotPassword: "¿Olvidaste tu contraseña?",
      signUpPrompt: "¿Recibiste una invitación?",
      signUpLink: "Crear cuenta",
    },
    signUp: {
      eyebrow: "Invitación",
      title: "Crea tu cuenta",
      description: "Completa tus datos con el correo que recibió la invitación.",
      submit: "Crear cuenta",
      submitting: "Enviando solicitud…",
      successTitle: "Revisa tu correo",
      success:
        "Si los datos corresponden a una invitación vigente, recibirás un enlace para verificar tu correo.",
      signInPrompt: "¿Ya tienes una cuenta?",
      signInLink: "Iniciar sesión",
    },
    verifyEmail: {
      eyebrow: "Verificación",
      title: "Verifica tu correo",
      description: "Abre el enlace que enviamos a tu correo para continuar.",
      verifiedTitle: "Correo verificado",
      verified: "Tu correo quedó verificado. Ya puedes iniciar sesión.",
      invalidTitle: "El enlace no es válido",
      invalid: "El enlace venció o ya fue utilizado. Puedes solicitar uno nuevo con tu correo.",
      resendTitle: "Enviar un enlace nuevo",
      resend: "Enviar enlace",
      resending: "Enviando enlace…",
      resendSuccess:
        "Si el correo corresponde a una cuenta pendiente, enviaremos un enlace de verificación.",
    },
    forgotPassword: {
      eyebrow: "Recuperación",
      title: "Recupera tu contraseña",
      description: "Escribe tu correo y te enviaremos instrucciones para continuar.",
      submit: "Enviar instrucciones",
      submitting: "Enviando instrucciones…",
      successTitle: "Revisa tu correo",
      success:
        "Si el correo corresponde a una cuenta, enviaremos un enlace para restablecer la contraseña.",
    },
    resetPassword: {
      eyebrow: "Recuperación",
      title: "Crea una contraseña nueva",
      description: "La nueva contraseña cerrará todas tus sesiones activas.",
      submit: "Guardar contraseña",
      submitting: "Guardando contraseña…",
      successTitle: "Contraseña actualizada",
      success: "Tu contraseña cambió y cerramos todas tus sesiones. Ya puedes iniciar sesión.",
      invalidTitle: "El enlace no es válido",
      invalid: "El enlace venció o ya fue utilizado. Solicita nuevas instrucciones para continuar.",
      requestNewLink: "Solicitar otro enlace",
    },
    security: {
      eyebrow: "Cuenta",
      title: "Seguridad de la cuenta",
      description:
        "Cambia tu contraseña. Cerraremos tus otras sesiones y mantendremos activa esta.",
      submit: "Cambiar contraseña",
      submitting: "Cambiando contraseña…",
      success: "Contraseña actualizada. Cerramos tus otras sesiones y esta sesión sigue activa.",
      error: "No pudimos cambiar la contraseña. Revisa tu contraseña actual e inténtalo de nuevo.",
    },
    roles: {
      admin: "Administrador",
      member: "Miembro",
    },
    route: {
      eyebrow: "Sesión",
      loading: "Cargando tu sesión",
      unavailableTitle: "No pudimos cargar tu sesión",
      unavailable:
        "El servicio no respondió como esperábamos. Inténtalo de nuevo en unos momentos.",
      retry: "Intentar de nuevo",
      deniedTitle: "Tu acceso no está activo",
      denied:
        "Tu cuenta no tiene acceso activo a este espacio de trabajo. Si crees que es un error, contacta al equipo responsable.",
      signOut: "Cerrar sesión",
      signingOut: "Cerrando sesión…",
      signOutError: "No pudimos cerrar la sesión. Inténtalo de nuevo.",
    },
  },
  conversations: {
    common: {
      newChat: "Nuevo chat",
      untitled: "Nuevo chat",
      retry: "Intentar de nuevo",
      loading: "Cargando conversaciones",
      loadMore: "Cargar más",
      loadingMore: "Cargando más…",
      empty: "Todavía no hay conversaciones.",
      genericError: "No pudimos cargar esta información. Inténtalo de nuevo.",
      changed:
        "La conversación cambió en otra pestaña. Actualizamos la información; revisa el estado e inténtalo de nuevo.",
    },
    navigation: {
      label: "Navegación de conversaciones",
      open: "Abrir menú",
      close: "Cerrar menú",
      collapse: "Contraer barra lateral",
      expand: "Expandir barra lateral",
      search: "Buscar chats",
      recent: "Recientes",
      archived: "Archivados",
      account: "Cuenta",
      security: "Seguridad de la cuenta",
      signOut: "Cerrar sesión",
      signingOut: "Cerrando sesión…",
      signOutError: "No pudimos cerrar la sesión. Inténtalo de nuevo.",
      signOutDraftError:
        "No cerramos la sesión porque el borrador aún no se pudo guardar. Inténtalo de nuevo.",
    },
    newChat: {
      documentTitle: "Nuevo chat",
      title: "¿En qué puedo ayudarte?",
      description: "Tu borrador se guarda de forma segura mientras escribes.",
    },
    draft: {
      label: "Borrador del mensaje",
      placeholder: "Escribe tu mensaje",
      loading: "Cargando borrador…",
      saving: "Guardando…",
      saved: "Borrador guardado",
      unsaved: "Cambios sin guardar",
      invalidText:
        "El borrador contiene texto no válido o caracteres de control. Corrígelo para guardarlo.",
      tooLarge: "El borrador supera el límite de 32 KB. Redúcelo para guardarlo.",
      retry: "Volver a guardar",
      conflictTitle: "El borrador cambió en otra pestaña",
      conflictDescription:
        "Elige cuál versión quieres conservar. No cambiaremos tu texto sin tu confirmación.",
      conflictLoadError: "El borrador cambió, pero todavía no pudimos obtener la versión guardada.",
      loadServer: "Cargar la versión guardada",
      keepServer: "Usar el borrador guardado",
      replaceServer: "Conservar este borrador",
      pendingNotice: "Hay cambios de borrador que todavía no se han guardado.",
    },
    generation: {
      actions: {
        send: "Enviar",
        sending: "Enviando…",
        stop: "Detener",
        stopping: "Deteniendo…",
        continue: "Continuar",
      },
      status: {
        starting: "Enviando mensaje…",
        generating: "Generando respuesta…",
        compacting: "Preparando el contexto…",
        stopping: "Deteniendo respuesta…",
        completed: "Respuesta completada",
        cancelled: "Respuesta detenida",
        interrupted: "La respuesta se interrumpió",
        protocolFailure: "La respuesta se interrumpió por un problema de conexión",
        failed: "No pudimos generar la respuesta",
        outputLimit: "La respuesta alcanzó su límite",
        archived: "Desarchiva la conversación para enviar un mensaje.",
        refreshing: "Actualizando la conversación…",
      },
      terminal: {
        cancelled: "Respuesta detenida",
        incomplete: "Respuesta interrumpida",
        failed: "Respuesta no generada",
        length: "La respuesta alcanzó su límite",
        refusal: "El asistente no pudo responder a esta solicitud",
        contentFilter: "La respuesta fue limitada por seguridad",
      },
      errors: {
        generic: "No pudimos iniciar la respuesta. Tu borrador sigue guardado.",
        ambiguous:
          "No pudimos confirmar si la respuesta comenzó. Revisa la conversación antes de volver a enviar.",
        conversationAmbiguous:
          "No pudimos confirmar si se creó la conversación. Revisa Recientes antes de volver a intentar.",
        committed: "No pudimos completar la respuesta.",
        archived: "Desarchiva la conversación antes de enviar el mensaje.",
        conversationChanged:
          "La conversación cambió. Actualiza la información y vuelve a intentarlo.",
        draftChanged: "El borrador cambió. Revisa la versión guardada antes de enviarlo.",
        active: "Ya hay una respuesta activa en esta conversación.",
        tooLarge:
          "El mensaje o el contexto de esta rama es demasiado largo. Redúcelo antes de enviarlo.",
        draftSave: "No pudimos confirmar el borrador. Tu texto permanece en el editor.",
        recovery: "No pudimos actualizar la conversación.",
        responseState: "No pudimos actualizar el estado de algunas respuestas.",
      },
    },
    conversation: {
      loading: "Cargando conversación",
      notFoundTitle: "No encontramos esta conversación",
      notFound: "Puede que haya sido eliminada o que ya no esté disponible para tu cuenta.",
      empty: "Esta conversación todavía no tiene mensajes.",
      older: "Cargar mensajes anteriores",
      userLabel: "Tú",
      assistantLabel: "Asistente",
      alternatives: (count: number) =>
        count === 1 ? "1 alternativa preservada" : `${count} alternativas preservadas`,
      actions: "Acciones de la conversación",
      rename: "Cambiar nombre",
      renameTitle: "Cambiar nombre de la conversación",
      titleLabel: "Nombre",
      titleHelp: "Usa una sola línea de hasta 120 caracteres.",
      saveTitle: "Guardar nombre",
      archive: "Archivar",
      unarchive: "Desarchivar",
      delete: "Eliminar",
      deleting: "Eliminando…",
      deleteTitle: "Eliminar conversación",
      deleteNotice:
        "Esta acción elimina la conversación de forma inmediata e irreversible. El contenido puede permanecer temporalmente en respaldos cifrados inaccesibles hasta que finalice su período de retención.",
      confirmDelete: "Eliminar definitivamente",
      cancel: "Cancelar",
    },
    archived: {
      documentTitle: "Conversaciones archivadas",
      title: "Conversaciones archivadas",
      description: "Puedes abrirlas, buscarlas o devolverlas a tus conversaciones recientes.",
      empty: "No hay conversaciones archivadas.",
    },
    search: {
      documentTitle: "Buscar chats",
      title: "Buscar chats",
      description: "Busca en nombres y mensajes de todas tus conversaciones preservadas.",
      label: "Buscar en conversaciones",
      placeholder: "Escribe para buscar",
      invalidText:
        "La búsqueda contiene texto no válido o caracteres de control. Corrígela para continuar.",
      tooLarge: "La búsqueda supera el límite de 256 bytes. Redúcela para continuar.",
      prompt: "Escribe una búsqueda para ver resultados.",
      loading: "Buscando…",
      empty: "No encontramos resultados.",
      archived: "Archivada",
      titleMatch: "Coincidencia en el nombre",
      messageMatch: "Coincidencia en un mensaje",
      open: "Abrir resultado",
      opening: "Abriendo resultado…",
    },
    network: {
      offline: "Sin conexión. Los cambios pendientes todavía no se han guardado.",
    },
  },
} as const;
