import Type from "typebox";

export const API_ERROR_CODES = {
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  BAD_REQUEST: "BAD_REQUEST",
  CONVERSATION_CHANGED: "CONVERSATION_CHANGED",
  DEVELOPMENT_MAILBOX_DENIED: "DEVELOPMENT_MAILBOX_DENIED",
  DRAFT_CHANGED: "DRAFT_CHANGED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_CURSOR: "INVALID_CURSOR",
  INVALID_EMAIL_OR_PASSWORD: "INVALID_EMAIL_OR_PASSWORD",
  JSON_REQUIRED: "JSON_REQUIRED",
  MEMBERSHIP_ACTIVATION_FAILED: "MEMBERSHIP_ACTIVATION_FAILED",
  NAME_REQUIRED: "NAME_REQUIRED",
  NOT_FOUND: "NOT_FOUND",
  ORIGIN_NOT_ALLOWED: "ORIGIN_NOT_ALLOWED",
  PASSWORD_TOO_LONG: "PASSWORD_TOO_LONG",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  SESSION_REFRESH_REQUIRED: "SESSION_REFRESH_REQUIRED",
  WORKSPACE_ACCESS_DENIED: "WORKSPACE_ACCESS_DENIED",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export const ApiErrorSchema = Type.Object(
  {
    code: Type.String({ minLength: 1 }),
    message: Type.String({ minLength: 1 }),
    requestId: Type.String({ minLength: 1 }),
  },
  { additionalProperties: false },
);

export type ApiError = Type.Static<typeof ApiErrorSchema>;
