import Type from "typebox";

export const API_ERROR_CODES = {
  ADMIN_ACCESS_REQUIRED: "ADMIN_ACCESS_REQUIRED",
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  BAD_REQUEST: "BAD_REQUEST",
  CATALOG_REFRESH_ACTIVE: "CATALOG_REFRESH_ACTIVE",
  CONTEXT_COMPACTION_FALLBACK: "CONTEXT_COMPACTION_FALLBACK",
  CONVERSATION_ARCHIVED: "CONVERSATION_ARCHIVED",
  CONVERSATION_CHANGED: "CONVERSATION_CHANGED",
  DEVELOPMENT_MAILBOX_DENIED: "DEVELOPMENT_MAILBOX_DENIED",
  DRAFT_CHANGED: "DRAFT_CHANGED",
  EMPTY_RESPONSE: "EMPTY_RESPONSE",
  EMPLOYEE_APPROVAL_CONFLICT: "EMPLOYEE_APPROVAL_CONFLICT",
  EMPLOYEE_DEACTIVATION_INCOMPLETE: "EMPLOYEE_DEACTIVATION_INCOMPLETE",
  EMPLOYEE_GENERATION_LIMIT_REACHED: "EMPLOYEE_GENERATION_LIMIT_REACHED",
  GENERATION_ACTIVE: "GENERATION_ACTIVE",
  GENERATION_ALREADY_EXISTS: "GENERATION_ALREADY_EXISTS",
  GENERATION_FAILED: "GENERATION_FAILED",
  GENERATION_TIMEOUT: "GENERATION_TIMEOUT",
  IDEMPOTENCY_KEY_INVALID: "IDEMPOTENCY_KEY_INVALID",
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_CURSOR: "INVALID_CURSOR",
  INVALID_EMAIL_OR_PASSWORD: "INVALID_EMAIL_OR_PASSWORD",
  INVITATION_DELIVERY_FAILED: "INVITATION_DELIVERY_FAILED",
  JSON_REQUIRED: "JSON_REQUIRED",
  MEMBERSHIP_ACTIVATION_FAILED: "MEMBERSHIP_ACTIVATION_FAILED",
  MESSAGE_TOO_LARGE: "MESSAGE_TOO_LARGE",
  MODEL_POLICY_CHANGED: "MODEL_POLICY_CHANGED",
  MODEL_POLICY_CONFLICT: "MODEL_POLICY_CONFLICT",
  MODEL_UNAVAILABLE: "MODEL_UNAVAILABLE",
  MODEL_VALIDATION_FAILED: "MODEL_VALIDATION_FAILED",
  NAME_REQUIRED: "NAME_REQUIRED",
  NOT_FOUND: "NOT_FOUND",
  ORIGIN_NOT_ALLOWED: "ORIGIN_NOT_ALLOWED",
  PASSWORD_TOO_LONG: "PASSWORD_TOO_LONG",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  SESSION_REFRESH_REQUIRED: "SESSION_REFRESH_REQUIRED",
  SESSION_REVOCATION_FAILED: "SESSION_REVOCATION_FAILED",
  SIGN_OUT_CANCELLATION_FAILED: "SIGN_OUT_CANCELLATION_FAILED",
  STREAM_INTERRUPTED: "STREAM_INTERRUPTED",
  STREAM_PROTOCOL_ERROR: "STREAM_PROTOCOL_ERROR",
  TIER_UNAVAILABLE: "TIER_UNAVAILABLE",
  WORKSPACE_ACCESS_DENIED: "WORKSPACE_ACCESS_DENIED",
  WORKSPACE_BUDGET_EXCEEDED: "WORKSPACE_BUDGET_EXCEEDED",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export const ApiErrorCodeSchema = Type.Enum(Object.values(API_ERROR_CODES));

export const ApiErrorSchema = Type.Object(
  {
    code: ApiErrorCodeSchema,
    message: Type.String({ minLength: 1 }),
    requestId: Type.String({ minLength: 1 }),
  },
  { additionalProperties: false },
);

export type ApiError = Type.Static<typeof ApiErrorSchema>;
