schema: 1
environment: production
name: capstone-chat-production
branch: app-platform-production
domain: chat.capstone.com.ec
service_size_slug: apps-s-1vcpu-1gb-fixed
job_size_slug: apps-s-1vcpu-0.5gb
dedicated_egress: true
service_environment:
  general:
    CAPSTONE_ENVIRONMENT: production
    PUBLIC_ORIGIN: https://chat.capstone.com.ec
    EMAIL_FROM: Capstone Chat <no-reply@mail.capstone.com.ec>
  secret_keys: []
