schema: 1
environment: staging
name: capstone-chat-staging
branch: app-platform-staging
domain: staging.chat.capstone.com.ec
service_size_slug: apps-s-1vcpu-0.5gb
job_size_slug: apps-s-1vcpu-0.5gb
dedicated_egress: false
service_environment:
  general:
    CAPSTONE_ENVIRONMENT: staging
    PUBLIC_ORIGIN: https://staging.chat.capstone.com.ec
    EMAIL_FROM: Capstone Chat Staging <no-reply@staging.mail.capstone.com.ec>
  secret_keys:
    - CAPSTONE_STAGING_EMAIL_RECIPIENTS
